[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
remappings = ["supply-chain-traceability/=node_modules/supply-chain-traceability/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
